export const BASE_FALLBACK_EXAMPLE = {
    examTitle: "Sample Exam",
    subject: "General",
    questions: [
        {
            id: "q_001",
            subtopicId: "subtopic_001",
            section: "Section A",
            questionText: "Sample question text testing a single, specific concept.",
            options: [
                { id: "A", text: "Option A" },
                { id: "B", text: "Option B" },
                { id: "C", text: "Option C" },
                { id: "D", text: "Option D" },
            ],
            correctOptionId: "C",
            marks: 1,
        },
        {
            id: "q_002",
            subtopicId: "subtopic_001",
            section: "Section A",
            questionText: "Another sample question with four options.",
            options: [
                { id: "A", text: "Option A" },
                { id: "B", text: "Option B" },
                { id: "C", text: "Option C" },
                { id: "D", text: "Option D" },
            ],
            correctOptionId: "B",
            marks: 2,
        },
        {
            id: "q_003",
            subtopicId: "subtopic_002",
            section: "Section B",
            questionText: "Identify the correct statement based on the given concept.",
            options: [
                { id: "A", text: "Option A" },
                { id: "B", text: "Option B" },
                { id: "C", text: "Option C" },
                { id: "D", text: "Option D" },
            ],
            correctOptionId: "D",
            marks: 2,
        },
        {
            id: "q_004",
            subtopicId: "subtopic_002",
            section: "Section B",
            questionText: "Choose the most appropriate answer.",
            options: [
                { id: "A", text: "Option A" },
                { id: "B", text: "Option B" },
                { id: "C", text: "Option C" },
                { id: "D", text: "Option D" },
            ],
            correctOptionId: "A",
            marks: 1,
        },
        {
            id: "q_005",
            subtopicId: "subtopic_003",
            section: "Section C",
            questionText: "Select the correct option for the given scenario.",
            options: [
                { id: "A", text: "Option A" },
                { id: "B", text: "Option B" },
                { id: "C", text: "Option C" },
                { id: "D", text: "Option D" },
            ],
            correctOptionId: "D",
            marks: 3,
        },
        {
            id: "q_006",
            subtopicId: "subtopic_003",
            section: "Section C",
            questionText: "Which of the following best satisfies the requirement?",
            options: [
                { id: "A", text: "Option A" },
                { id: "B", text: "Option B" },
                { id: "C", text: "Option C" },
                { id: "D", text: "Option D" },
            ],
            correctOptionId: "B",
            marks: 2,
        }
    ],
};