import { z } from "zod";

/**
 * ---------------------------------------------------------
 * Shared Types
 * ---------------------------------------------------------
 */

const BaseQuestionSchema = z.object({
    /**
     * Sequential ID generated by the model.
     * Example:
     * q_001
     * q_002
     */
    id: z.string(),

    /**
     * Helps us validate that the model generated
     * questions for the correct subtopic.
     */
    subtopicId: z.string(),

    /**
     * Helps us validate that the question belongs
     * to the expected section.
     */
    section: z.string(),

    /**
     * Actual question text.
     */
    questionText: z.string(),
});

/**
 * ---------------------------------------------------------
 * MCQ
 * ---------------------------------------------------------
 */

export const MCQOptionSchema = z.object({
    id: z.enum(["A", "B", "C", "D"]),
    text: z.string(),
});

export const MCQQuestionSchema = BaseQuestionSchema.extend({
    type: z.literal("mcq"),

    /**
     * Exactly four options.
     */
    options: z.array(MCQOptionSchema).length(4),

    /**
     * Must be one of A,B,C,D
     */
    correctOptionId: z.enum(["A", "B", "C", "D"]),
});

/**
 * ---------------------------------------------------------
 * Subjective
 * ---------------------------------------------------------
 */

export const SubjectiveQuestionSchema = BaseQuestionSchema.extend({
    type: z.literal("subjective"),
});

/**
 * ---------------------------------------------------------
 * Union
 * ---------------------------------------------------------
 */

export const GeneratedQuestionSchema = z.discriminatedUnion("type", [
    MCQQuestionSchema,
    SubjectiveQuestionSchema,
]);

/**
 * ---------------------------------------------------------
 * Output
 * ---------------------------------------------------------
 */

export const GenerationOutputSchema = z.object({
    questions: z.array(GeneratedQuestionSchema),
});

/**
 * ---------------------------------------------------------
 * Types
 * ---------------------------------------------------------
 */

export type MCQOption = z.infer<typeof MCQOptionSchema>;

export type MCQQuestion = z.infer<typeof MCQQuestionSchema>;

export type SubjectiveQuestion = z.infer<typeof SubjectiveQuestionSchema>;

export type GeneratedQuestion = z.infer<typeof GeneratedQuestionSchema>;

export type GenerationOutput = z.infer<typeof GenerationOutputSchema>;